# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - run: ls
#     - name: Copy single file to remote
#       uses: garygrossgarten/github-action-scp@release
#       with:
#         local: build/libs/dataworker-1.jar
#         remote: /root/app/
#         host: ${{ secrets.HOST }}
#         username: ${{ secrets.SSH_USER }}
#         password: ${{ secrets.PASSWORD }}
    - run: ls build/libs
    - name: Copy file via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.SSH_USER }}
        KEY: ${{ secrets.PASSWORD }}
      with:
        source: "build/libs"
        target: "/root/app"
